DO NOT READ IF YOU ARE AN END USER IT SPOILS THE GAME

* Setting
  In the kingdom of Wiek, split into 5 regions in the point of a
  star. There are other regions around it. The time period is unknown, but
  their technology is around the 14th century's technology. The main
  village(unnamed as of now) is in the bottom left region, nearly in the
  middle of the 1 big start, yet still in the bottom left point.

*** Hero background
    Hero is roughly 8 to 10 years old at the start of the game. Game will
    employ a timewarp mechanism to get the player to a more sensible age
    for parts of the game.

*** Village background
    Village hero grows up in has a tradition of martial arts and starts
    showing their children to fight around age 8 to 10.

*** TODO Family background

*** Initial timeline
    1) start with no weapons in home village
    2) first battles is against a trainer
       1) player is meant to interact with the environment
    3) Maybe do a simple mission like apprehend a robber
       1) Possibly make this guy the ultimate antagonist?


*** Later timeline
    - Sister gets captured, hero tries to save her and fails.

* Weapons
  - Use sticks/stones/other parts of the environment
  - slingshot
  - wood sword from father

*** More general...
    We have a concept of:
    - Hand to hand fighting
    - close in weapons like swords/nunchucks
    - ranged weapons like slingshot/rocks/bow-arrow/stars
    - artillery?
    - bombs
    - traps

* puzzles
  We want to work in some sort of puzzles and things to make player think
  some.

* Characters
  - Wiek :: is the "Kingdom".
  - Igoru :: is the hero.
  - Irisi :: is the princess.
  - namehere :: first trainer/village elder
  - namehere :: father
  - namehere :: mother
  - namehere :: sister1
  - namehere :: sister2
  - namehere :: older brother (dies during a war)
  - namehere :: robber (start of game, first "mission")


* Races or groups of people
  - Initial village


* Ideas / general concept possibilities
  - hero leads for a short time some sort of army of followers.
  - Hero enters various dungeons.
  - antagonist controls someone else to trick the player.
